apiVersion: v1
kind: Service
metadata:
  name: mlproject-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8501  # Port where your Streamlit app runs
  selector:
    app: mlproject
